In [2]:
import numpy as np

In [3]:
#Convert a 1D array to a 2D array with 2 rows

a=np.arange(20)
a=a.reshape(2,-1)
#-1 automatically decides number of columns
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [4]:
#Stack arrays a and b vertically

b = np.arange(10).reshape(2,-1)
c = np.arange(10).reshape(2,-1)
np.vstack([b, c])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
#Stack the arrays a and b horizontally

d = np.arange(10).reshape(2,-1)
e = np.arange(10).reshape(2,-1)
np.hstack([d, e]


SyntaxError: unexpected EOF while parsing (<ipython-input-5-dad54338b4ca>, line 5)

In [6]:
f = np.array([1,2,3])
np.r_[np.repeat(f, 3), np.tile(f, 4)]



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [7]:
#get common items

g = np.array([1,2,3,2,3,4,3,4,5,6])
h = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(g,h)


array([2, 4])

In [8]:
#From array i remove all items present in array j

i = np.array([1,2,3,9,5])
j = np.array([5,6,7,8,9])

np.setdiff1d(i,j)

array([1, 2, 3])

In [9]:
#Get all items between 5 and 10 from k

k = np.array([2, 6, 1, 9, 10, 3, 27])
k[(k >= 5) & (k <= 10)]



array([ 6,  9, 10])

In [10]:
#Reverse the rows of a 2D array l
l = np.arange(9).reshape(3,3)
l[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [16]:
#Import the iris dataset keeping the text intact

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [18]:
print ('Concatenate two strings:' )
print (np.char.add(['hello'],[' xyz'])) 

print ('Concatenation example:' )
print (np.char.add(['hello', 'hi'],[' abc', ' xyz']))


Concatenate two strings:
['hello xyz']
Concatenation example:
['hello abc' 'hi xyz']


In [19]:
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:' )
print (a )

print ('After rounding:' )
print (np.around(a) )
print (np.around(a, decimals = 1) )
print (np.around(a, decimals = -1))


Original array:
[  1.      5.55  123.      0.567  25.532]
After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
