In [1]:
import numpy as np

In [8]:
#multidimentional arrays
a=np.array([[3,4],[8,7]])
print(a)
print(a.shape)
print(a.T)
print(np.linalg.inv(a) )
print(np.linalg.det(a) )
print(np.diag(a))

[[3 4]
 [8 7]]
(2, 2)
[[3 8]
 [4 7]]
[[-0.63636364  0.36363636]
 [ 0.72727273 -0.27272727]]
-10.999999999999996
[3 7]


In [14]:
#slicing
b=np.array([[5,7,],[2,3]])
print(b)
c=b[0,1]
print(c)
d=b[0,:]
print(d)
bool_index=b>=5
print(bool_index)

[[5 7]
 [2 3]]
7
[5 7]
[[ True  True]
 [False False]]


In [18]:
#reshaping
e=np.arange(1,7)
print(e)
print(e.shape)
print(e.reshape(2,3))
print(e.shape)
f=e[np.newaxis,:1]
print(f)
print(f.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(6,)
[[1]]
(1, 1)


In [25]:
#concatenation
g=np.array([[3,5],[2,4]])
print(g)
h=np.array([[9,8]])
i=np.concatenate((g,h.T),axis=1)
print(i)

[[3 5]
 [2 4]]
[[3 5 9]
 [2 4 8]]


In [27]:
#hstack #vstack #broadcasting
j=np.array([9,9,0,3,4])
k=np.array([5,3,7,1,4])
print(np.hstack([j,k]))
print(np.vstack([j,k]))
l=np.array([[3,4,5],[1,3,5],[3,5,2],[3,4,7]])
m=np.array([4,2,8])
n=l+m
print(n)

[9 9 0 3 4 5 3 7 1 4]
[[9 9 0 3 4]
 [5 3 7 1 4]]
[[ 7  6 13]
 [ 5  5 13]
 [ 7  7 10]
 [ 7  6 15]]


In [29]:
#functionsandaxis
o=np.array([[3,5,4,6,7,8],[2,4,4,5,5,6]])
print(o)
print(o.sum(axis=0))
print(o.sum(axis=1))

[[3 5 4 6 7 8]
 [2 4 4 5 5 6]]
[ 5  9  8 11 12 14]
[33 26]


In [33]:
#datatypes
p=np.array([4,5,0.3],dtype=np.int64)
print(p)
print(p.dtype)

[4 5 0]
int64


In [37]:
#copying
q=np.array([4,5,6])
r=q.copy()
r[0]=9
print(r)
print(q)

[9 5 6]
[4 5 6]


In [39]:
#randomnumbers
s=np.random.random((3,2))
print(s)

[[0.21721079 0.22432134]
 [0.26375682 0.68685688]
 [0.96846974 0.5019209 ]]
