In [1]:
import numpy as np 

In [2]:
a=np.array([8,9,0,3,4,5])
print(a)

[8 9 0 3 4 5]


In [3]:
print(a[4])

4


In [4]:
import time 
import sys

In [7]:
b=range(1000)
print(sys.getsizeof(12)*len(b))

28000


In [8]:
c=np.arange(1000)
print(c.itemsize*c.size)

8000


In [14]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
d = np.array([('juvbnn', 18, 90),('fxfchn', 19, 75)], dtype = student) 
print(d)


[(b'juvbnn', 18, 90.) (b'fxfchn', 19, 75.)]


In [16]:
e = np.array([[5,6,7,8],[1,4,5,6]]) 
print (e.shape)


(2, 4)


In [17]:
f = np.array([[1,2,3],[4,5,6]]) 
f.shape = (3,2) 
print (f) 


[[1 2]
 [3 4]
 [5 6]]


In [18]:
f = np.array([[1,2,3],[4,5,6]]) 
f.shape = (2,3) 
print (f) 



[[1 2 3]
 [4 5 6]]


In [20]:
g = np.arange(50) 
print (g)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [23]:
g = np.arange(24) 
# now reshaping it 
g = g.reshape(2,4,3) 
print(g)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [25]:
h=np.arange(5, 100, 5, int)
print(h)


[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [28]:
i= np.arange(10) 
j = i[5] 
print (j)


5


In [30]:
k = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (k) 
print ('slicing the array from the index k[1:]' )
print (k[1:])


[[1 2 3]
 [3 4 5]
 [4 5 6]]
slicing the array from the index k[1:]
[[3 4 5]
 [4 5 6]]


In [31]:
l = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('array is' )
print (l)
print ('items in the second column are' ) 
print (l[...,1] )
print ('items in the second row are' )
print (l[1,...])
print ('items from column 1 onwards are' )
print (l[...,1:])


array is
[[1 2 3]
 [3 4 5]
 [4 5 6]]
items in the second column are
[2 4 5]
items in the second row are
[3 4 5]
items from column 1 onwards are
[[2 3]
 [4 5]
 [5 6]]


In [33]:
m = np.array([[1, 8], [0, 9], [7, 6]]) 
n = m[[0,1,2], [0,1,0]] 
print (n)


[1 9 7]


In [36]:
o = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print (o)
print ('items greater than 6 are' )
print (o[o > 6])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
items greater than 6 are
[ 7  8  9 10 11]


In [44]:
p = np.arange(0,60,5) 
p = p.reshape(3,4) 
print (p)
print ('transpose of the original array is' )
q = p.T 
print(q)
print ('iterating over the array is')
for x in np.nditer(q): 
   print (x)


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
transpose of the original array is
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
iterating over the array is
0
5
10
15
20
25
30
35
40
45
50
55
